FROM sopir-base:latest

WORKDIR /app

COPY backend ./backend
COPY dashboard ./dashboard

ENV PYTHONPATH=/app

EXPOSE 8501

CMD ["streamlit", "run", "dashboard/app.py", "--server.port=8501", "--server.address=0.0.0.0"]